title: Wkwang'Tech Log
author: Weikang Wang
baseurl: "/tech-log"
description: conclusion of engineering and technic staff
profile_url: "http://Wei-kang-Wang.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
